export const FETCH_NEWSSTOCK_LIST = 'FETCH_NEWSSTOCK_LIST';
export const FETCH_NEWSSTOCK_LIST_SUCCESS = 'FETCH_NEWSSTOCK_LIST_SUCCESS';
export const FETCH_NEWSSTOCK_LIST_ERROR = 'FETCH_NEWSSTOCK_LIST_ERROR';

// Login and Auth Data
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const INCREASE_PAGE_NUMBER = 'INCREASE_PAGE_NUMBER';
